name: Deploy to GitHub Pages

on:
  push:
    paths:
      - 'coffee-shop-landing-page.zip'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip site
        run: unzip -o coffee-shop-landing-page.zip -d site

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm' # you have pnpm-lock.yaml

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: cd site && pnpm install

      - name: Build project
        run: cd site && pnpm build
        # This creates a "dist" folder

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site/dist'  # Upload the built files, not source

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
